AWSTemplateFormatVersion: 2010-09-09
Resources:
  Ec2Instance:
    Type: AWS::EC2::Instance
    DependsOn: Fn::GetAtt: InstanceSecurityGroup.GroupId
    Properties:
      ImageId: "ami-08a52ddb321b32a8c"
      InstanceType: "t2.micro"
      KeyName: "Mylaptopkey"
      Monitoring: True
      SecurityGroups: "Infra-man-instance-sg"
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      VpcId: DefaultVpc
      GroupName: Infra-man-instance-sg
      GroupDescription: This securtiy group check rules for management instance for our Infra
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
      - IpProtocol: "-1"
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0x